name: Snapshot Release

on: pull_request

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Prepare artifacts
        run: yarn build

      - name: Release a snapshot
        run: |
          yarn changeset version --snapshot pr${{ github.event.pull_request.number }}
          yarn changeset publish --tag pr${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
